---
- name: Enable Repo (RedHat)
  include_tasks:
    file: tasks/RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Ensure Yadm Is Present
  become: true
  package: name="{{ yadm_pkg_name }}" state=present
