---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Update Apt Cache
      apt: update_cache=yes cache_valid_time=360
      when: ansible_os_family == 'Debian'
      changed_when: false
  roles:
    - role: hwwilliams.yadm
  tasks:
    - name: Ensure Yadm Is Installed
      command: yadm --version
      register: yadm_version
      failed_when: yadm_version.rc != 0